### PR TITLE
Add support for secrets

### PR DESCRIPTION
**Pull request by wjervis7**
Added support for secrets, similar to https://github.com/diinngg/nordvpn/commit/b6c4e274d8df3a0e2448758cb1716ef5f217c912

(sorry for all the commits, I'm rather new to git, and this is my first time contributing to another repository.  If I did something wrong, please let me know)

### CODE REVIEW

**Comment by wjervis7** [comment]
Also, I created a PR, earlier, without meaning to.  Sorry if that caused confusion.  I tried to close it, ASAP, once I realized it wasn't merging to my fork :|

**Comment by mafrasi2** [comment]
Thank you for your work! That's exactly what I needed.

I'm not the maintainer, so I don't know for sure whether this is what's holding this back, but I think it would make sense to squash these commits into a single one. For example like this:

    git rebase -i 550d7540b56ff6f1eaba2eb5782d33cbc6dcb41e

Then change `pick` to `squash` in lines 2-10, close the file and set a new commit message for the entire pull request in the second step. After that, you will have to force push:

    git push --force

**Comment by Mladia** [comment]
Can someone merge this if it works please.

**Comment by bubuntux** [comment]
@Mladia have you tested it?

**Comment by wjervis7** [comment]
I have this image, that I've been using, since I created the PR: wjervis7/nordlynx:latest

**Comment by wjervis7** [comment]
> Thank you for your work! That's exactly what I needed.
> 
> I'm not the maintainer, so I don't know for sure whether this is what's holding this back, but I think it would make sense to squash these commits into a single one. For example like this:
> 
> ```
> git rebase -i 550d7540b56ff6f1eaba2eb5782d33cbc6dcb41e
> ```
> 
> Then change `pick` to `squash` in all lines except the first, close the file and set a new commit message for the entire pull request in the second step. After that, you will have to force push:
> 
> ```
> git push --force
> ```

I'm not sure if I did this right :|

**Pull request merged**
