### PR TITLE
Update Dockerfile with iptables legacy fix

### PR DESCRIPTION
**Pull request by w1mm3r**
took fix from wireguard repo
https://github.com/linuxserver/docker-wireguard/blob/master/Dockerfile

Credit to @arkandias for pointing to the fix
https://github.com/bubuntux/nordlynx/pull/178/files#r1874405959

### CODE REVIEW

**Comment by w1mm3r** [comment]
Works just fine.

...:~/projects/nordlynx-iptables$ docker logs nordlynx 
[migrations] started
[migrations] no migrations found
[2024-12-22T20:58:18+00:00] Firewall is up, everything has to go through the vpn
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
...
[2024-12-22T20:58:18+00:00] Enabling connection to secure interfaces
[2024-12-22T20:58:18+00:00] No interface network6 detected
...
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[2024-12-22T20:58:19+00:00] Finding the best server...
[2024-12-22T20:58:19+00:00] Server: {
...
[2024-12-22T20:58:19+00:00] Connecting...
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[#] 
[2024-12-22T20:58:19+00:00] Connected! \(ᵔᵕᵔ)/
...:~/projects/nordlynx-iptables$ docker exec -it nordlynx bash
root@9cf75c944f4f:/# ping google.com
PING google.com (192.0.0.88): 56 data bytes
64 bytes from 192.0.0.88: seq=0 ttl=64 time=19.947 ms
64 bytes from 192.0.0.88: seq=1 ttl=64 time=19.744 ms
64 bytes from 192.0.0.88: seq=2 ttl=64 time=19.739 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 19.739/19.810/19.947 ms
root@9cf75c944f4f:/# ping api.nordvpn.com
PING api.nordvpn.com (104.16.208.203): 56 data bytes
64 bytes from 104.16.208.203: seq=0 ttl=56 time=23.197 ms
64 bytes from 104.16.208.203: seq=1 ttl=56 time=23.118 ms
64 bytes from 104.16.208.203: seq=2 ttl=56 time=22.905 ms
^C
--- api.nordvpn.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 22.905/23.073/23.197 ms

**Comment by fletch3555** [comment]
@bubuntux Any chance we can get this merged and a new release cut? Current version is unusable.

**Review by fletch3555 — APPROVED** [review]
LGTM!

**Comment by JackMBurch** [comment]
@w1mm3r Looks like this might still happening, getting 

```
iptables v1.8.10 (legacy): host/network `api.nordvpn.com' not found
Try `iptables -h' or 'iptables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
iptables v1.8.10 (legacy): host/network `api.nordvpn.com' not found
Try `iptables -h' or 'iptables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
```

Docker compose file:

```yml
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx:latest # build: ~/qbittorrent/nordlynx
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PRIVATE_KEY=#############
      - TOKEN=###################    # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
      - 8081:8081
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recommended if using ipv4 only
    restart: unless-stopped
```

Full logs:
```
[migrations] started
[migrations] no migrations found
[2025-02-24T18:07:44+00:00] Firewall is up, everything has to go through the vpn
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────
[2025-02-24T18:07:44+00:00] Enabling connection to eth0 172.18.0.2/16

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────
[2025-02-24T18:07:44+00:00] Enabling connection to secure interfaces

User UID:    911
User GID:    911
───────────────────────────────────────
iptables v1.8.10 (legacy): host/network `api.nordvpn.com' not found
Try `iptables -h' or 'iptables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
```

**Comment by w1mm3r** [comment]
> @w1mm3r Looks like this might still happening, getting
> 
> ```
> iptables v1.8.10 (legacy): host/network `api.nordvpn.com' not found
> Try `iptables -h' or 'iptables --help' for more information.
> Seems like we have no internet connection. Retrying in 5 seconds...
> iptables v1.8.10 (legacy): host/network `api.nordvpn.com' not found
> Try `iptables -h' or 'iptables --help' for more information.
> Seems like we have no internet connection. Retrying in 5 seconds...
> ```
> 
> Docker compose file:
> 
> ```yaml
> services:
>   nordlynx:
>     image: ghcr.io/bubuntux/nordlynx:latest # build: ~/qbittorrent/nordlynx
>     cap_add:
>       - NET_ADMIN               # Required
>       - NET_RAW                 # Required
>     environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
>       - PRIVATE_KEY=#############
>       - TOKEN=###################    # Required
>       - CONNECT=United_States
>       - TECHNOLOGY=NordLynx
>       - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
>     ports:
>       - 8080:8080
>       - 8081:8081
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=1  # Recommended if using ipv4 only
>     restart: unless-stopped
> ```
> 
> Full logs:
> 
> ```
> [migrations] started
> [migrations] no migrations found
> [2025-02-24T18:07:44+00:00] Firewall is up, everything has to go through the vpn
> usermod: no changes
> ───────────────────────────────────────
>   _____ __ __ _____ _____ _____ _____ 
>  |     |  |  |   __|_   _|     |     |
>  |   --|  |  |__   | | | |  |  | | | |
>  |_____|_____|_____| |_| |_____|_|_|_|
>        _____ __ __ _ __    ____  
>       | __  |  |  | |  |  |    \ 
>       | __ -|  |  | |  |__|  |  |
>       |_____|_____|_|_____|____/ 
> 
>   Based on images from linuxserver.io
> ───────────────────────────────────────
> [2025-02-24T18:07:44+00:00] Enabling connection to eth0 172.18.0.2/16
> 
> To support the app dev(s) visit:
> Bubuntux: https://github.com/sponsors/bubuntux
> WireGuard: https://www.wireguard.com/donations/
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> [2025-02-24T18:07:44+00:00] Enabling connection to secure interfaces
> 
> User UID:    911
> User GID:    911
> ───────────────────────────────────────
> iptables v1.8.10 (legacy): host/network `api.nordvpn.com' not found
> Try `iptables -h' or 'iptables --help' for more information.
> Seems like we have no internet connection. Retrying in 5 seconds...
> ```

Can you run ```ip a```?
So we can se your ip config
What environment are you running in?
WSL in windows 11 or linux box or windows docker desktop
What are we up against :)

I myself was running in WSL on windows 11, but latest update killed bridge network mode in WSL so now I am struggling with mirrored network mode...

**Pull request merged**
